// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sut.system.domain;

import org.springframework.beans.factory.annotation.Configurable;
import sut.system.domain.LogItem;

privileged aspect LogItem_Roo_Configurable {
    
    declare @type: LogItem: @Configurable;
    
}
