// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sut.system.domain;

import sut.system.domain.Payment;

privileged aspect Payment_Roo_JavaBean {
    
    public String Payment.getPrice() {
        return this.price;
    }
    
    public void Payment.setPrice(String price) {
        this.price = price;
    }
    
}
